#!/bin/bash

start() {
    echo -n "Setting hostname: "

    sn=$(cat /proc/cpuinfo | grep Serial | tr -d ' ' | cut -d ':' -f 2)
    sn=${sn: -8}
    hostname="mp-$sn"
    /bin/hostname $hostname
    echo "Welcome to $hostname!" > /var/cache/sshd_banner
    echo "send host-name = \"$hostname\";" > /var/cache/dhclient.conf

    echo "done"
}

stop() {
    echo -n
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
