#!/bin/sh
#
# SD card image builder for rpi-buildroot
#
# Guillermo A. Amaral B. <g@maral.me>
#

# sanaty check
if [ ${UID} -ne 0 ]; then
	echo "${0} requires root privileges in order to work."
	exit 0
fi

section() {
	sync
	echo "*****************************************************************************************"
	echo "> ${*}"
	echo "*****************************************************************************************"
	sleep 1
}

# overrides
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
IMAGE="sdcard.img"
OUTPUT_PREFIX=""

if [ -z "${SIZE}" ]; then
    SIZE="64M"
fi

echo "Creating ${SIZE} size image..."
sleep 3

# dependencies
CP=`which cp`
DD=`which dd`
MOUNT=`which mount`
UMOUNT=`which umount`
MKDIR=`which mkdir`
RMDIR=`which rmdir`
FDISK=`which fdisk`
LOSETUP=`which losetup`
MKFS_EXT4=`which mkfs.ext4`
MKFS_VFAT=`which mkfs.vfat`
TAR=`which tar`

if [ -z "${CP}" ] ||
   [ -z "${DD}" ] ||
   [ -z "${MOUNT}" ] ||
   [ -z "${UMOUNT}" ] ||
   [ -z "${MKDIR}" ] ||
   [ -z "${RMDIR}" ] ||
   [ -z "${FDISK}" ] ||
   [ -z "${LOSETUP}" ] ||
   [ -z "${MKFS_EXT4}" ] ||
   [ -z "${MKFS_VFAT}" ] ||
   [ -z "${TAR}" ]; then
	echo "Missing dependencies:\n"
	echo "CP=${CP}"
	echo "DD=${DD}"
	echo "MOUNT=${MOUNT}"
	echo "UMOUNT=${UMOUNT}"
	echo "MKDIR=${MKDIR}"
	echo "RMDIR=${RMDIR}"
	echo "FDISK=${FDISK}"
	echo "LOSETUP=${LOSETUP}"
	echo "MKFS_EXT4=${MKFS_EXT4}"
	echo "MKFS_VFAT=${MKFS_VFAT}"
	echo "TAR=${TAR}"
	exit 1
fi

# sanity check
if [ ! -f "images/rootfs.tar" ]; then
	if [ -f "output/images/rootfs.tar" ]; then
		OUTPUT_PREFIX="output/"
	else
		echo "Didn't find boot and/or rootfs.tar! ABORT."
		exit 1
	fi
fi

# find loop device
LOOP=`${LOSETUP} -f`

# create image
${DD} if=/dev/zero of=${IMAGE} bs=${SIZE} count=1

# partition image
${FDISK} ${IMAGE} <<END
o
n
p
1

+32M
n
p
2


t
1
e
a
1
w
END

# loop image
${LOSETUP} -P ${LOOP} ${IMAGE} || exit 1

# format partitions

section "Formatting partitions..."

${MKFS_VFAT} -F 16 -n BOOT -I "${LOOP}p1" || exit 1
${MKFS_EXT4} -L rootfs "${LOOP}p2" || exit 1

${MKDIR} .mnt

# fill boot

section "Populating boot partition..."

${MOUNT} "${LOOP}p1" .mnt || exit 2
${CP} ${OUTPUT_PREFIX}images/boot/* .mnt
${UMOUNT} .mnt

# fill rootfs

section "Populating rootfs partition..."

${MOUNT} "${LOOP}p2" .mnt || exit 2
${TAR} -xvpsf ${OUTPUT_PREFIX}images/rootfs.tar -C .mnt
${UMOUNT} .mnt

${SYNC}

${RMDIR} .mnt

# unmount
${LOSETUP} -D

section "Finished!"

exit 0
