#!/bin/sh

sys_static_conf="/etc/net_watchdog.conf"
static_conf="/data/etc/net_watchdog.conf"
retries=3
timeout=5
interval=20

if [ -f $sys_static_conf ] && ! [ -f $static_conf ]; then
    mkdir -p $(dirname $static_conf)
    cp $sys_static_conf $static_conf
fi

if [ -f $static_conf ]; then
    source $static_conf
else
    exit
fi

watch() {
    count=0
    retries=$(($retries - 1))
    while true; do
        if nc -n -w $timeout $host $port </dev/null >/dev/null 2>&1; then
            count=0
        else
            if [ $count -lt $retries ]; then
                count=$(($count + 1))
                continue
            else
                logger -t netwatchdog -s "cannot connect to $host:$port, rebooting"
                reboot
            fi
        fi
        sleep $interval
    done
}

case "$1" in
    start)
        echo -n "Starting netwatchdog: "
        watch &
        echo "done"
        ;;

    stop)
        echo -n "Stopping netwatchdog: "
        ps | grep netwatchdog | grep -v $$ | grep -v grep | tr -s ' ' | cut -d ' ' -f 2 | xargs -r kill
        echo "done"
        ;;

    restart|reload)
        "$0" stop
        "$0" start
        ;;
        
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

