#!/bin/bash

start() {
    echo -n "Setting hostname: "

    sn="cubietruck"
    echo $sn > /var/cache/serial_number
    hostname="mp-$sn"
    /bin/hostname $hostname
    echo "127.0.0.1 localhost motionpie $hostname" > /etc/hosts

    echo "done"
}

stop() {
    echo -n
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
