#!/bin/sh


# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
for i in $(ls -r /etc/init.d/S??*) ;do
    [ ! -f "$i" ] && continue
    [ -f /data/etc/no_$(basename $i) ] && continue

     case "$i" in
        *.sh) # Source shell script for speed.
            (
            trap - INT QUIT TSTP
            set stop
            . $i
            )
            ;;
        *) # No sh extension, so fork subprocess.
            $i stop
            ;;
    esac
done

