#!/bin/bash

start() {
    echo -n "Setting hostname: "
    sn=$(vcgencmd otp_dump | grep 28: | tail -c +4)
    hostname="motioneye$sn"
    /bin/hostname $hostname
    echo "done"
}

stop() {
    echo -n
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

