#!/bin/bash

DISK_DEV="/dev/mmcblk0"
DATA_DEV="${DISK_DEV}p3"
set +e

# don't execute the script if kernel cmdline has "nodatapart" keyword
if /bin/cat /proc/cmdline | /bin/grep "nodatapart"; then
    exit;
fi


start() {
    echo "Setting up data partition"

    # if the partition is not present, allocate it and issue a reboot
    if ! [ -b $DATA_DEV ]; then
        echo "Allocating data partition"
        echo -e "n
    p
    3
    \n
    \n
    w
    " | /sbin/fdisk $DISK_DEV
        sync
        reboot -f
    fi

    # if the filesystem is not valid (not yet formatted), format it
    if /usr/sbin/debugfs -R 'lcd /' $DATA_DEV 2>&1 | grep 'Bad magic'; then
        echo "Formatting data partition"
        mkfs.ext4 $DATA_DEV

        mount /data # also mount it
        
        # create necessary directories
        mkdir -p /data/etc
        mkdir -p /data/output
        mkdir -p /data/media

        echo "Setting root password..."
        echo 'root::::::::' > /data/etc/shadow
        chmod go-rwx /data/etc/shadow
        pwd=$(/opt/vc/bin/vcgencmd otp_dump | grep 28: | tail -c +4)
        echo -en "$pwd\n$pwd\n" | passwd
        # removes password expiration
        sed -r -i 's/root:([^:]+):[[:digit:]]+:/root:\1::/' /data/etc/shadow
    fi
}

stop() {
    echo -n
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload)
        restart
        ;;
  
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

