#!/bin/sh

mkdir -p /var/lib/dhcp
config="/var/cache/dhclient.conf"

start_lo() {
    ifconfig lo up
}

start_wlan0() {
    if [ "$(cat /sys/class/net/wlan0/carrier 2>/dev/null)" != "1" ]; then
        echo "wlan0: no carrier"
        return
    fi
    
    echo "wlan0: starting dhclient"
    dhclient -cf "/var/cache/dhclient.conf" wlan0
}

start_eth0() {
    # wait for driver
    count=0
    while ! ifconfig eth0 >/dev/null 2>&1 && [ $count -lt 3 ]; do
        sleep 1
        count=$(($count + 1))
    done
    
    if ! ifconfig eth0 >/dev/null 2>&1; then
        echo "eth0: no device"
        return # no device
    fi

    # bring it up
    ifconfig eth0 up
    
    # wait for carrier
    count=0
    while [ "$(cat /sys/class/net/eth0/carrier 2>/dev/null)" != "1" ] && [ $count -lt 3 ]; do
        sleep 1
        count=$(($count + 1))
    done
    
    if [ "$(cat /sys/class/net/eth0/carrier 2>/dev/null)" != "1" ]; then
        echo "eth0: no carrier"
        return # no carrier
    fi
    
    echo "eth0: starting dhclient"
    dhclient -cf "/var/cache/dhclient.conf" eth0
}

start() {
    start_lo
    start_wlan0
    start_eth0

    # print the current network configuration
    ifconfig -a
}

case "$1" in
    start)
        echo -n "Starting network: "
        start
        echo "done"
        ;;

    stop)
        echo -n "Stopping network: "
        killall dhclient
        echo "done"
        ;;

    restart|reload)
        "$0" stop
        "$0" start
        ;;
        
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

