#!/bin/sh

conf="/etc/sshd_config"

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

# Check for the SSH1 RSA key
if [ ! -f /data/etc/ssh_host_key ] ; then
    echo "Generating HOST Key..."
    /usr/bin/ssh-keygen -t rsa1 -f /data/etc/ssh_host_key -C '' -N ''
fi

# Check for the SSH2 RSA key
if [ ! -f /data/etc/ssh_host_rsa_key ] ; then
    echo "Generating RSA Key..."
    /usr/bin/ssh-keygen -t rsa -f /data/etc/ssh_host_rsa_key -C '' -N ''
fi

# Check for the SSH2 DSA key
if [ ! -f /data/etc/ssh_host_dsa_key ] ; then
    echo "Generating DSA Key..."
    /usr/bin/ssh-keygen -t dsa -f /data/etc/ssh_host_dsa_key -C '' -N ''
fi

# Check for the SSH2 ECDSA key
if [ ! -f /data/etc/ssh_host_ecdsa_key ]; then
    echo "Generating ECDSA Key..."
    /usr/bin/ssh-keygen -t ecdsa -f /data/etc/ssh_host_ecdsa_key -C '' -N ''
fi

# Check for the ed25519 key
if [ ! -f /data/etc/ssh_host_ed25519_key ]; then
    echo "Generating ed25519 Key..."
    /usr/bin/ssh-keygen -t ed25519 -f /data/etc/ssh_host_ed25519_key -C '' -N ''
fi

umask 077

start() {
    echo -n "Starting sshd: "
    /usr/sbin/sshd -f $conf
    touch /var/lock/sshd
    echo "done"
}
stop() {
    echo -n "Stopping sshd: "
    killall sshd
    rm -f /var/lock/sshd
    echo "done"
}
restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
