#!/bin/sh

[ -f /etc/ntp.conf ] || exit 0

mkdir -p /var/lib/ntp

set_current_date() {
    timestamp=$(python -c 'import calendar, httplib, email.utils; conn = httplib.HTTPConnection("google.com"); conn.request("HEAD", "/"); \
            print calendar.timegm(email.utils.parsedate(conn.getresponse().getheader("date")))')
    
    date +%s -s @$timestamp > /dev/null
}

start() {
    echo -n "Setting current date: "
    set_current_date
    [ $? == 0 ] && date || echo "failed"

    echo -n "Starting ntpd: "
    ntpd -g -c /etc/ntp.conf
    [ $? == 0 ] && echo "done" || echo "failed"
}

stop() {
    echo -n "Shutting down ntpd: "
    kill `pidof ntpd` 2>/dev/null
    [ $? == 0 ] && echo "done" || echo "failed"
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart)
        restart
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
