#! /bin/sh

[ -f /etc/vsftpd.conf ] || exit 0

set -e

case "$1" in
    start)
        echo -n "Starting vsftpd: "
        vsftpd /etc/vsftpd.conf
        [ $? == 0 ] && echo "done" || echo "failed"
        ;;

    stop)
        echo -n "Stopping vsftpd: "
        killall vsftpd
        [ $? == 0 ] && echo "done" || echo "failed"
        ;;

    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0

