#!/bin/sh
#
# Start watchdog
#

case "$1" in
 start)
	echo -n "Starting watchdog: "
	watchdog -t 5 /dev/watchdog
	echo "done"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
